import type { Post } from '../../components/common/PostCard/PostCard.types';

export const seedPosts: Post[] = [
  {
    id: 101,
    title: 'Waymo launches world’s first fully autonomous ride-hailing',
    text: 'Driverless taxi service operates 24/7 with perfect safety record across major cities.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=101',
    lesson_num: 1,
    author: 1,
  },
  {
    id: 102,
    title: 'Figure 03 robot marks major leap in dexterity',
    text: 'Advanced AI + tactile sensors reach near-human grasping.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=102',
    lesson_num: 1,
    author: 2,
  },
  {
    id: 103,
    title: 'Revolutionary quantum dot solar tiles',
    text: 'Higher efficiency, lower cost, modular rooftops.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=103',
    lesson_num: 1,
    author: 3,
  },
  {
    id: 104,
    title: 'Microsoft unveils revolutionary chip packaging',
    text: '3D stacking with liquid interposers amps bandwidth.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=104',
    lesson_num: 1,
    author: 4,
  },
  {
    id: 105,
    title: 'SpaceX Starship completes crucial splashdown test',
    text: 'Thermal protection learns from the wild ride.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=105',
    lesson_num: 1,
    author: 5,
  },
  {
    id: 106,
    title: 'React Testing Library, best practices in 2025',
    text: 'Accessible queries first, less mocking, more confidence.',
    date: '2025-06-21',
    image: 'https://picsum.photos/640/360?random=106',
    lesson_num: 1,
    author: 6,
  },
];
