import type { Post } from '../../components/common/PostCard/PostCard.types';

export const seedPosts: Post[] = [
  {
    id: 101,
    title: 'Waymo launches world\'s first fully autonomous ride-hailing',
    text: 'Driverless taxi service operates 24/7 with perfect safety record across major cities.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=101',
    lesson_num: 1,
    author: 1,
    likes: 42,
    dislikes: 3,
  },
  {
    id: 102,
    title: 'Figure 03 robot marks major leap in dexterity',
    text: 'Advanced AI + tactile sensors reach near-human grasping.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=102',
    lesson_num: 1,
    author: 2,
    likes: 28,
    dislikes: 1,
  },
  {
    id: 103,
    title: 'Revolutionary quantum dot solar tiles',
    text: 'Higher efficiency, lower cost, modular rooftops.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=103',
    lesson_num: 1,
    author: 3,
    likes: 156,
    dislikes: 7,
  },
  {
    id: 104,
    title: 'Microsoft unveils revolutionary chip packaging',
    text: '3D stacking with liquid interposers amps bandwidth.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=104',
    lesson_num: 1,
    author: 4,
    likes: 89,
    dislikes: 12,
  },
  {
    id: 105,
    title: 'SpaceX Starship completes crucial splashdown test',
    text: 'Thermal protection learns from the wild ride.',
    date: '2025-10-20',
    image: 'https://picsum.photos/640/360?random=105',
    lesson_num: 1,
    author: 5,
    likes: 203,
    dislikes: 5,
  },
  {
    id: 106,
    title: 'React Testing Library, best practices in 2025',
    text: 'Accessible queries first, less mocking, more confidence.',
    date: '2025-06-21',
    image: 'https://picsum.photos/640/360?random=106',
    lesson_num: 1,
    author: 6,
    likes: 67,
    dislikes: 2,
  },
  // Дополнительные посты для тестирования пагинации
  {
    id: 107,
    title: 'AI-powered code review revolutionizes development',
    text: 'Machine learning algorithms catch bugs before they reach production.',
    date: '2025-10-19',
    image: 'https://picsum.photos/640/360?random=107',
    lesson_num: 2,
    author: 7,
    likes: 134,
    dislikes: 8,
  },
  {
    id: 108,
    title: 'Next.js 15 introduces revolutionary server components',
    text: 'Zero JavaScript bundles, instant page loads, better SEO.',
    date: '2025-10-19',
    image: 'https://picsum.photos/640/360?random=108',
    lesson_num: 2,
    author: 8,
    likes: 298,
    dislikes: 15,
  },
  {
    id: 109,
    title: 'TypeScript 5.5 brings advanced type inference',
    text: 'Improved developer experience with smarter type checking.',
    date: '2025-10-18',
    image: 'https://picsum.photos/640/360?random=109',
    lesson_num: 2,
    author: 9,
    likes: 187,
    dislikes: 6,
  },
  {
    id: 110,
    title: 'WebAssembly 2.0 enables native performance in browsers',
    text: 'Faster execution, smaller bundles, better security.',
    date: '2025-10-18',
    image: 'https://picsum.photos/640/360?random=110',
    lesson_num: 3,
    author: 10,
    likes: 245,
    dislikes: 12,
  },
  {
    id: 111,
    title: 'CSS Container Queries revolutionize responsive design',
    text: 'Component-based responsive design without media queries.',
    date: '2025-10-17',
    image: 'https://picsum.photos/640/360?random=111',
    lesson_num: 3,
    author: 11,
    likes: 156,
    dislikes: 4,
  },
  {
    id: 112,
    title: 'GraphQL Federation 2.0 simplifies microservices',
    text: 'Better schema composition, improved developer experience.',
    date: '2025-10-17',
    image: 'https://picsum.photos/640/360?random=112',
    lesson_num: 3,
    author: 12,
    likes: 178,
    dislikes: 9,
  },
  {
    id: 113,
    title: 'Docker Desktop introduces Kubernetes integration',
    text: 'Seamless container orchestration for local development.',
    date: '2025-10-16',
    image: 'https://picsum.photos/640/360?random=113',
    lesson_num: 4,
    author: 13,
    likes: 203,
    dislikes: 11,
  },
  {
    id: 114,
    title: 'Redis 7.4 adds advanced caching strategies',
    text: 'Better performance, improved memory management.',
    date: '2025-10-16',
    image: 'https://picsum.photos/640/360?random=114',
    lesson_num: 4,
    author: 14,
    likes: 167,
    dislikes: 7,
  },
  {
    id: 115,
    title: 'PostgreSQL 16 introduces advanced partitioning',
    text: 'Better query performance, improved scalability.',
    date: '2025-10-15',
    image: 'https://picsum.photos/640/360?random=115',
    lesson_num: 4,
    author: 15,
    likes: 189,
    dislikes: 5,
  },
  {
    id: 116,
    title: 'MongoDB 7.2 enhances aggregation pipeline',
    text: 'More powerful data processing capabilities.',
    date: '2025-10-15',
    image: 'https://picsum.photos/640/360?random=116',
    lesson_num: 5,
    author: 16,
    likes: 145,
    dislikes: 8,
  },
  {
    id: 117,
    title: 'Elasticsearch 8.12 improves search performance',
    text: 'Faster queries, better relevance scoring.',
    date: '2025-10-14',
    image: 'https://picsum.photos/640/360?random=117',
    lesson_num: 5,
    author: 17,
    likes: 198,
    dislikes: 6,
  },
  {
    id: 118,
    title: 'Kubernetes 1.30 adds advanced scheduling',
    text: 'Better resource allocation, improved cluster efficiency.',
    date: '2025-10-14',
    image: 'https://picsum.photos/640/360?random=118',
    lesson_num: 5,
    author: 18,
    likes: 234,
    dislikes: 13,
  },
];
